name: Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "37 7 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    name: Check links
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Markdown and HTML links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-mail './README.md' './src/**/*.html'
